import assert from "node:assert/strict";
import { mkdtemp, mkdir, readFile, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import test from "node:test";
import { ingestLibrary } from "../../ingest/src/ingest.ts";
import { createUiServer } from "./server.ts";

test("serves catalog observations and export previews", async () => {
  const root = await mkdtemp(join(tmpdir(), "retroroms-ui-"));
  const source = join(root, "source"); const processed = join(root, "processed");
  await mkdir(source); await writeFile(join(source, "Super Metroid (USA) [En].sfc"), "rom");
  const summary = await ingestLibrary({ sourceRoots: [source], processedRoot: processed });
  const ui = await createUiServer({ libraryPath: summary.catalogPath, port: 0 });
  const address = ui.server.address(); const port = typeof address === "object" && address ? address.port : 0;
  const observations = await (await fetch(`http://127.0.0.1:${port}/api/observations`)).json() as { observations: Array<{ id: string; title: string; seriesKey: string }> };
  assert.equal(observations.observations[0].title, "Super Metroid");
  assert.equal(observations.observations[0].seriesKey, "super metroid");
  const preview = await (await fetch(`http://127.0.0.1:${port}/api/export-preview`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ ids: [observations.observations[0].id], policy: "compressed" }) })).json() as { plan: Array<{ outputFormat: string }> };
  assert.equal(preview.plan[0].outputFormat, "zip");
  const history = await (await fetch(`http://127.0.0.1:${port}/api/exports`)).json() as { exports: unknown[] };
  assert.equal(history.exports.length, 0);
  const stats = await (await fetch(`http://127.0.0.1:${port}/api/stats`)).json() as { observationCount: number; preferredEditionCount: number };
  assert.equal(stats.observationCount, 1);
  assert.equal(stats.preferredEditionCount, 1);
  const scans = await (await fetch(`http://127.0.0.1:${port}/api/scans`)).json() as { scans: Array<{ status: string }> };
  assert.equal(scans.scans[0]?.status, "completed");
  const warnings = await (await fetch(`http://127.0.0.1:${port}/api/warnings`)).json() as { warnings: unknown[] };
  assert.equal(warnings.warnings.length, 0);
  const artworkBefore = await (await fetch(`http://127.0.0.1:${port}/api/artwork/settings`)).json() as { configured: boolean };
  assert.equal(artworkBefore.configured, false);
  const artworkSaved = await (await fetch(`http://127.0.0.1:${port}/api/artwork/settings`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ theGamesDbApiKey: "local-test-key" }) })).json() as { configured: boolean };
  assert.equal(artworkSaved.configured, true);
  const artworkAfter = await (await fetch(`http://127.0.0.1:${port}/api/artwork/settings`)).json() as { configured: boolean };
  assert.equal(artworkAfter.configured, true);
  const scrape = await (await fetch(`http://127.0.0.1:${port}/api/artwork/scrape`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ ids: [] }) })).json() as { results: unknown[] };
  assert.equal(scrape.results.length, 0);
  const profilePreview = await (await fetch(`http://127.0.0.1:${port}/api/export-preview`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ ids: [observations.observations[0].id], profiles: { unknown: { outputPolicy: "uncompressed" } } }) })).json() as { plan: Array<{ outputFormat: string }> };
  assert.equal(profilePreview.plan[0].outputFormat, "raw");
  const exported = await (await fetch(`http://127.0.0.1:${port}/api/export`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ ids: [observations.observations[0].id], policy: "uncompressed" }) })).json() as { results: Array<{ status: string; destinationRelativePath: string }> };
  assert.equal(exported.results[0].status, "exported");
  assert.equal(await readFile(join(processed, exported.results[0].destinationRelativePath), "utf8"), "rom");
  const retry = await (await fetch(`http://127.0.0.1:${port}/api/export`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ ids: [observations.observations[0].id], policy: "uncompressed" }) })).json() as { results: Array<{ status: string }> };
  assert.equal(retry.results[0].status, "skip-existing");
  await writeFile(join(processed, exported.results[0].destinationRelativePath), "different");
  const conflict = await (await fetch(`http://127.0.0.1:${port}/api/export`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ ids: [observations.observations[0].id], policy: "uncompressed" }) })).json() as { results: Array<{ status: string }> };
  assert.equal(conflict.results[0].status, "conflict");
  const overwrite = await (await fetch(`http://127.0.0.1:${port}/api/export`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ ids: [observations.observations[0].id], policy: "uncompressed", overwriteConflicts: true }) })).json() as { results: Array<{ status: string }> };
  assert.equal(overwrite.results[0].status, "exported");
  await ui.close();
});
